#########################################################3
###############3 This is the makefile for the serial project
############ g++ main.cpp serialGA.h -o serial ###########
##########################################################
CC=g++
DEPS=serialGA.h

serial: main.cpp serialGA.cpp $(DEPS)
	$(CC) -o serial main.cpp serialGA.cpp $(DEPS)